### ISSUE TITLE
Leading Whitespace in watch expression still causes parse error

### ISSUE THREAD

**Issue by lrajlich** [aeisenberg/angular-bind-notifier#29] opened 2016-05-20 20:55 UTC
I found an issue with leading whitespace - https://github.com/kasperlewau/angular-bind-notifier/issues/28 does not fix the issue. The expression now passes the regex check here https://github.com/kasperlewau/angular-bind-notifier/blob/master/src/bindNotifier.js#L112 but the parts variable declared here https://github.com/kasperlewau/angular-bind-notifier/blob/master/src/bindNotifier.js#L116 a " " in index 0 which means it passes the "not falsey" check a few lines below.

This problem can be solved by doing a whitespace-only regex check along with the "not falsey" check - line 121 now is
 `if (part && /^(\w+\S+)$/.test(part)) {`

**Comment by lrajlich** [comment] 2016-05-20 21:07
That regex logic is incorrect, here's the right line:

```
if (part && /^\s*$/.test(part) == false) {
```

**Comment by lrajlich** [comment] 2016-05-20 21:15
Or alternatively you could just trim the whitespace from the expression? http://www.w3schools.com/jsref/jsref_trim_string.asp

**Comment by ibnclaudius** [comment] 2016-11-04 23:55
I'm having the same problem here.

**Comment by aeisenberg** [comment] 2018-03-15 18:32
I just had this problem and I can confirm that @lrajlich's fix works for me. 

I have a slight bias towards using .trim() instead of regex because it would seem to be faster, but since I don't actually have data to back that up, I'm not saying this very strongly.

@lrajlich, if you can add a test for this, perhaps we can get this merged? If you're no longer interested in working on this, I will take this over and add the test.

**Comment by aeisenberg** [comment] 2018-03-15 18:40
So, ran some rough jsperf tests on regex vs trim. 

https://jsperf.com/regex-vs-trim-for-bind-notifier/1

Trim comes out about 5% faster. Difference is not big, but since these expressions tend to be in performance critical sections, it might be important.

**Comment by aeisenberg** [comment] 2018-03-17 14:01
That's my pull request with a test.

**Comment by aeisenberg** [comment] 2018-03-21 19:36
Merged. I've been given control over this project and merged the PR. This will go into the 1.1.9 release.

**Closed by aeisenberg** 2018-03-21 19:36 UTC
